---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        POSTGRES_DB: &dbName odoo
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser "{{ .ODOO_POSTGRESQL_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .ODOO_POSTGRESQL_PASSWORD }}"
        DB: &dbName odoo
        HOST: *dbHost
        PORT: "5432"
        USER: *dbUser
        PASSWORD: *dbPass
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## odoo
    - secretKey: ODOO_POSTGRESQL_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e8830296-eba7-4924-9fba-937d93e7a31d
        property: ODOO_POSTGRESQL_USER
    - secretKey: ODOO_POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e8830296-eba7-4924-9fba-937d93e7a31d
        property: ODOO_POSTGRESQL_PASSWORD