---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: odoo
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        strategy: RollingUpdate

        pod:
          enableServiceLinks: false

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: odoo-secret

        containers:
          main:
            image:
              repository: docker.io/odoo/odoo
              tag: 17.0
            envFrom:
              - secretRef:
                  name: odoo-secrets
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 256M

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "internal"
        # annotations:
        #   external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "odoo.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: emptyDir
        # existingCLaim: odoo-config-v1
        # mountPath: /var/lib/odoo
      etc-config-file:
        enabled: true
        type: emptyDir
      #   type: configMap
      #   name: odoo-configmap
      #   mountPath: /etc/odoo/odoo.conf
      #   subPath: odoo.conf
      #   readOnly: true
      extra-addons:
        enabled: true
        type: emptyDir       
        # existingClaim: odoo-addons-v1
        # mountPath: /mnt/extra-addons

## EXECUTE ME
### odoo /var/www/odoo/bin/console doctrine:migrations:migrate --env=prod --no-interaction

### php bin/console odoo:install --env=prod