# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app paperless
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/media/paperless/app
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 15Gi
#       VOLSYNC_STORAGECLASS: smb-paperless
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: paperless-redis
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: "./kubernetes/apps/media/paperless/redis"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: true
#   dependsOn:
#     - name: cluster-apps-external-secrets-stores

