---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        NEXTCLOUD_POSTGRESQL_NAME: &dbName nextcloud-db
        NEXTCLOUD_POSTGRESQL_HOST: &dbHost postgres-rw.database.svc.cluster.local
        NEXTCLOUD_POSTGRESQL_USER: &dbUser "{{ .NEXTCLOUD_POSTGRESQL__USER }}"
        NEXTCLOUD_POSTGRESQL_PASSWORD: &dbPass "{{ .NEXTCLOUD_POSTGRESQL__PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## NEXTCLOUD
    - secretKey: NEXTCLOUD_POSTGRESQL_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 207c99ee-07fc-4c18-8888-2bd8cd19a931
        property: NEXTCLOUD_POSTGRESQL_USER
    - secretKey: NEXTCLOUD_POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 207c99ee-07fc-4c18-8888-2bd8cd19a931
        property: NEXTCLOUD_POSTGRESQL_PASSWORD