---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: media
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: nextcloud-redis.media.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "nextcloud-secret"
              key: NEXTCLOUD_REDIS_PASSWORD
      # existingSecret:
      #   enabled: true
      #   secretName: nextcloud
      host: &host nextcloud.${SECRET_DOMAIN}
      mail:
        enabled: false
        fromAddress: admin
        domain: ${SECRET_DOMAIN}
        smtp:
          host: smtp.${SECRET_DOMAIN}
          port: 587
          authtype: tls
          name: ""
          password: ""
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:14.9
          envFrom:
            - secretRef:
                name: nextcloud-secret
    # redis:
    #   enabled: true
    #   auth:
    #     enabled: true
    #     redis.auth.existingSecret: nextcloud-secret
    #     redis.auth.existingSecretPasswordKey: NEXTCLOUD_REDIS_PASSWORD
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: 'postgresql'
      existingSecret:
        enabled: true
        database: nextcloud
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_POSTGRESQL_USER
        passwordKey: NEXTCLOUD_POSTGRESQL_PASSWORD
        hostKey: NEXTCLOUD_POSTGRESQL_HOST
        databaseKey: NEXTCLOUD_POSTGRESQL_NAME
    ingress:
      enabled: true
      className: "internal"
      # servicePort: http
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array('${SERVICE_CIDR}')
          );
      annotations:
        external-dns.alpha.kubernetes.io/target: "nextcloud.${SECRET_DOMAIN}"
        # nginx.ingress.kubernetes.io/proxy-buffering: "off"
        # nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: false
      existingClaim: pvc-smb-nextcloud
      # nextcloudData:
      #   enabled: true
      #   existingClaim: pvc-smb-nextcloud
      #   accessMode: ReadWriteMany
  # valuesFrom:
  #   - targetPath: externalDatabase.user
  #     kind: Secret
  #     name: nextcloud
  #     valuesKey: database-username
  #   - targetPath: externalDatabase.password
  #     kind: Secret
  #     name: nextcloud
  #     valuesKey: database-password