---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: media
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: 192.168.1.11
        - name: REDIS_HOST_PORT
          value: "6379"
      # existingSecret:
      #   enabled: true
      #   secretName: nextcloud
      host: &host nextcloud.${SECRET_DOMAIN}
      mail:
        enabled: false
        fromAddress: admin
        domain: ${SECRET_DOMAIN}
        smtp:
          host: pfsense.${SECRET_DOMAIN}
          port: 25
          authtype: NONE
          name: ""
          password: ""
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:14.9
          envFrom:
            - secretRef:
                name: nextcloud-secret
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: 'postgresql'
      existingSecret:
        enabled: false
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_POSTGRESQL_USER
        passwordKey: NEXTCLOUD_POSTGRESQL_PASSWORD
        hostKey: NEXTCLOUD_POSTGRESQL_HOST
        databaseKey: NEXTCLOUD_POSTGRESQL_NAME
    ingress:
      enabled: true
      className: "internal"
      annotations:
        external-dns.alpha.kubernetes.io/target: "nextcloud.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: pvc-smb-nextcloud
      # nextcloudData:
      #   enabled: true
      #   existingClaim: pvc-smb-nextcloud
      #   accessMode: ReadWriteMany
  # valuesFrom:
  #   - targetPath: externalDatabase.user
  #     kind: Secret
  #     name: nextcloud
  #     valuesKey: database-username
  #   - targetPath: externalDatabase.password
  #     kind: Secret
  #     name: nextcloud
  #     valuesKey: database-password