---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ../../../../templates/postgres-database
configMapGenerator:
  - name: autobrr-configmap
    files:
      - ./config/config.toml
generatorOptions:
  disableNameSuffixHash: true
