---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-secret
  namespace: kube-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        domain: |-
          {{ .domain }}
        password: |-
          {{ .password }}
  refreshInterval: 15m
  data:
    - secretKey: domain
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a2abda25-071d-43dd-84ba-45ebab1255be
        property: domain
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: a2abda25-071d-43dd-84ba-45ebab1255be
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a2abda25-071d-43dd-84ba-45ebab1255be
        property: samba