---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-media
  namespace: media
spec:
  storageClassName: "smb-media"
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-vol-media  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: //smb.${SECRET_DOMAIN}/services
      # subDir: media
    nodeStageSecretRef:
      name: smb-secret
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: pv-smb-media
  storageClassName: "smb-media"
