---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-redis
  namespace: security
spec:
  target:
    name: authentik-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_REDIS_PASSWORD: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
  data:
     ## AUTHENTIK
    - secretKey: AUTHENTIK_REDIS_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f3fcbd57-d2b1-48ae-acce-d3579d01ba33
        property: AUTHENTIK_REDIS_PASSWORD