---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: authentik-nextcloud
  app.kubernetes.io/instance: authentik