ansible_become_pass: ENC[AES256_GCM,data:bpQXKSaP39WyVjxIBriZ,iv:Qbj4MJy+t1YSneiC5vN6eCcBfYis6otZploEpemKuKQ=,tag:FNVwxzsYVAH/kwVbmxDqgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVTcxbHZnaVA5M2x4U2ly
            QjhFcTlzc29qaVBnaURud3kvSHZVWE1vV0NBCk9nOXdwem9DcHEwb3lqVldkcXBt
            Z0Q2ZVdicExQaklGRU5HY0lJMnlSOFUKLS0tIGFQbGxiclFlRGdZVEdydE1PUnRm
            blZ4ejVydFZVQXBpTEdZNDVTMnpzL0kKQ+L8yb1jr+K4eQdWhB1sWL5LcBd25b/a
            XZuTUiANn5ogM7dufKz6PRlmJyEmG+AeDA3klegYHSF7wRtnHUl5xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:53:17Z"
    mac: ENC[AES256_GCM,data:HJCs5OzwM+CgyWWRC86q/ySLaCnRPpgWXMeXdDG3pvq7nMkm945dSK1VFRbc6kjtjrxomMHN2REwtz7lOD25HGQuRoHzOr1DQ9XQ83mLI1FutZwX1vr4KQqDEgng080K+aljT9cOAPalxaBT9vBi9DErxi9mcysrUJ834ddpZFk=,iv:tKiMh/rVerttqPJOSRZziMyzOiPhdS5fh088CC3CTNk=,tag:fuz4TEBvsJBqU7NhaLTtIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
