ansible_become_pass: ENC[AES256_GCM,data:FnVhs5fqeFzttXwig8O3,iv:dmd8QfOLuJi79mp9biujB+jV71jE0m9nxQKMluoyVGo=,tag:mhsNFqFhJQd4KazeAARvHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQnVkNXFkOHZqZW15OHZk
            cWNrZGZPOWtreFpRL25idHB1d1E0bCtaaEdNCnlqZnFxN0VBZWR0VnhYS2U0amtu
            a0R5WGF1Z2tqTTJuMlVNQWRFK1lSZnMKLS0tIFByT3ZKRk5oWjMyVTdZdFU4cUZZ
            R2R4RDIyY0JnV1NaU2hPdnBabmRtam8Ktqcw5LtMHlhmcGcDGgpWp3kMvfvvCM9A
            y2LDBkN/1dngCE53ot14HVZ5dC8vGkbqmjIUCrUvFa5Y3EivHNPziQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T09:55:46Z"
    mac: ENC[AES256_GCM,data:zCh8J9nXmOXvlHOLMG3wBX+TimOWVLY8k49VREUeRr6PJbK4u+iSSsnQqx0GQkGrHP2qAv53e7jZE/upsxJ+uKLExkiNMJlaz1G6pQg3KdfEWii8Wg5wmJkMQbv8+wxfVKcW+BBv0V9v8oM+Tn/CwBhyI15SJUOZy7Ib2mrp780=,iv:EYUrB3tiHJl/PTknLIhBsvDYW+LPM2V/9QTwd8663WI=,tag:mLUT+xHwwvDQ0D95tWXySQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
