ansible_become_pass: ENC[AES256_GCM,data:7NVPr8wzVwT31hBT//gc,iv:8LDWn0Y7t5KrbAoAAC7ZJNUVtTjMsRW5A713QfrEC4g=,tag:v8o0ZDYorDZQBfMpnzzrhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ2lpUU9oTkh4d2syOWQ2
            ZnBjT0w0Ti9aeTIxZGNhVml0YzR5a1RJakQwCmZFMm82T1huSW1OZ0FjRnF6Yyt4
            N0MvRGY5ekdoY3RzTWU0Y0M0Tm03MUUKLS0tIDFxajVGcXZBQUhQL0pwMXc3cGdM
            SGVTNExMU0NJL1dzbXY4NjFzMjlyd2MKbFxu3AL5FdnZM5F3fol6XjgUw+WKRtWt
            BoFwyZm/6ApIxFlvyh3XfCvNKcr482yz7JIQ9scehwvGrIYwxy0+WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T14:11:30Z"
    mac: ENC[AES256_GCM,data:Hr4pPdKeetedqNR022Obm2cF+U2gKL16LdmnuSmdsYIvk6kmPOVMzzDueVbc1pI9yJkVyQKfFMyqMklUcJL44KlzI38/N9xi+BjKa103qcRsGmZNnyH+kg/+/cfxS1+FjAayAv1424bAaqI1IKBx9HOc6PK9E+26/w3MoJQeUiI=,iv:WasF1JkJw+csMS/yKVE1XtXQkHCygyQRTHmIJxYUI2k=,tag:jEhgWFoNSUMV3R3fSp4ROg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
