ansible_become_pass: ENC[AES256_GCM,data:qj7IXO9AJS2oUawhWhd4,iv:InX6k67tf8CdyHaOX/ml/4Ajmi/0sudzQHNFI4MPtUY=,tag:yISdYReq2cC7CMxHeY3tFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDlzY25jUVJKcGxJNU8v
            Z00yUVJQeDBXTTNYM1ArSWNpOUpZMUNjcXlJCmVEaHRXblhFcjdHR0JTbUZvYnRU
            WGx0RnRjZjhPd2oySGg4WGo5alRQZkUKLS0tIDB0aXNXR0JvZk5pdjRtall6SlZ2
            d3JOQm5wZ21qYWN0T09pU2hMZWFlc2MKZbMxzIrNR4X8n1ZKQ0jk6fA+g2sUsVXQ
            tVeNuIkXplyQiozSb0zlCYLnoXPEijRzMF3ysFrPF10hedlyBuxr6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T21:27:31Z"
    mac: ENC[AES256_GCM,data:cW4b/BcFlNb1qr70MAPWsQzoXIjdTuj6rmxrMC4qF62cwHqmU1c2I1nZWHuFicLvuDgsPEMRfpdXk0U9WGD41c3IN5nQufpHE/EyCld4welpynGEluBuUW7SI8e4g04ApKSFWinD+rb1y/JESxbEyXTO4oMl2uBYpk4ypdd54gs=,iv:/xYWxIfCgiawi7htY40fLZ37fVDOOXFspg8yp5rRJyk=,tag:vFSnez79yjOqWtTTwBYnHw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
