ansible_become_pass: ENC[AES256_GCM,data:ML8Ix5se3kgl/ZPK/Stu,iv:eKQ/gwFAnEXb37BWqjkmg3jX92CQCgB0JigudSh0kmc=,tag:YcUjljJKF0SghBl7UQ05mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUk1GTnB4MHdtaWhKbExH
            alloVXViQWpzM3EwWTlDL2JXbXNXMHd4clVVClV1bVdSb05oL3YrS3M1cDR6c0hO
            ZDl2UkVtTDVadVpJSEl5ZFFTdWhmM2MKLS0tIDk5ZjgxUWo4bjlrY0RKYjNWODlj
            a0dJQXZST05TSHo1Vm02dDVHaDh5Y0kKcGSrLpOwTgNA7e2TrkKeIYaUs/e2pqoG
            NCEeTdEzXQCkK5E22XHglm2q1syU11Xo+UngKN1mFFBlhbEPEbyb6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T09:55:48Z"
    mac: ENC[AES256_GCM,data:igLltcdLoEWnf1tRm4KenvHyGwgMXcpQOzfk9RkiUgcsZGKOSXqgMpmFhDh9AQcUdIshGAxdIJ/GCIfFeqgg5aLcOAzrhBDE5fAYS9OFciS59jvq7r91hi7Skc0+bf2mo8maYyzS89R7WYvwEc3CsXahE50y/cKhSQD6cwP1TjA=,iv:obcvMCoes/rtdheeis0FtwOY/E7PTwb/Rimp6YLmTxs=,tag:KkMTtAsyT6Zw/Oul9bUvYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
