---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-application


helmChartInflationGenerator:
  - chartName: app-template
    chartRepoUrl: https://bjw-s.github.io/helm-charts
    chartVersion: 1.3.2
    releaseName: it-tools
    releaseNamespace: internal-application
    values: values.yaml
#   - ingress.yaml
#   - external-svc.yaml
