---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tabby
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: tabby

    controllers:
      main:
        replicas: 1
        type: deployment
        strategy: Recreate
        containers:
          main:
            nameOverride: tabby
            image:
              repository: docker.io/tabbyml/tabby
              tag: latest
              pullPolicy: IfNotPresent
            command: ["/opt/tabby/bin/tabby"]
            args: ["serve", "--model", "TabbyML/CodeLlama-7B"]
            ports:
            - containerPort: 8080
            # resources:
            #   limits:
            #     nvidia.com/gpu: 1
            #     cpu: 7
            #     memory: 28Gi
            #   requests:
            #     nvidia.com/gpu: 1
            #     cpu: 1
            #     memory: 4Gi
            probes:
              readiness:
                enabled: false
              startup:
                enabled: false
              liveness:
                enabled: false # Need to get this working
                custom: false
                type: TCP
                spec:
                  initialDelaySeconds: 120
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 3


    service:
      main:
        enabled: true
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "tabby.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: emptyDir
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 500Mi
