---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
        # POSTGRES_SUPER_USER: "{{ .username }}"
        # POSTGRES_SUPER_PASS: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b63d3bff-0027-4779-8d0f-c70528bf98f8
        property: password
