---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
  namespace: media
data:
  # Configure application
  PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
  PAPERLESS_PORT: "8000"
  PAPERLESS_TIME_ZONE: "Asia/Kuala_Lumpur"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_TASK_WORKERS: "2"

  # # Configure Remote User auth
  # PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
  # PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME

  # Configure folders
  PAPERLESS_CONSUMPTION_DIR: /data/media/consume
  # PAPERLESS_DATA_DIR: /data/local/data
  PAPERLESS_EXPORT_DIR: /data/media/export
  # PAPERLESS_MEDIA_ROOT: /data/local/media

  # Configure folder importer
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"

  # Configure OCR
  PAPERLESS_OCR_LANGUAGES: nld
  PAPERLESS_OCR_LANGUAGE: nld

  # # Configure redis integration
  # PAPERLESS_REDIS: redis://paperless-redis.selfhosted.svc.cluster.local:6379

  # Configure user permissions
  USERMAP_GID: "65543"
