---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_DBHOST: |-
          {{ .dbHost }}
        PAPERLESS_DBPORT: |-
          {{ .dbPort }}
        PAPERLESS_DBNAME: |-
          {{ .dbName }}
        PAPERLESS_DBUSER: |-
          {{ .dbUser }}
        PAPERLESS_DBPASS: |-
          {{ .dbPass }}
        PAPERLESS_ADMIN_USER: |-
          {{ .adminUserName }}
        PAPERLESS_ADMIN_PASSWORD: |-
          {{ .adminPassword }}
        PAPERLESS_REDIS: |-
          {{ .redis_url }}
  refreshInterval: 15m
  data:
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: redis_url
    - secretKey: dbHost
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: dbHost
    - secretKey: dbPort
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: dbPort
    - secretKey: dbName
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: dbName
    - secretKey: dbUser
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: dbUser
    - secretKey: dbPass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: dbPass
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: redis_url
    - secretKey: adminUserName
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: username
    - secretKey: adminPassword
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 83a07794-c962-435b-98b4-45bc3322d197
        property: password