---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_DBHOST: &dbHost "{{ .dbHost }}"
        PAPERLESS_DBPORT: |-
          {{ .dbPort }}
        PAPERLESS_DBNAME: &dbName "{{ .dbName }}"
        PAPERLESS_DBUSER: &dbUser "{{ .dbUser }}"
        PAPERLESS_DBPASS: &dbPass "{{ .dbPass }}"
        PAPERLESS_ADMIN_USER: |-
          {{ .adminUserName }}
        PAPERLESS_ADMIN_PASSWORD: |-
          {{ .adminPassword }}
        PAPERLESS_REDIS: |-
          {{ .redis_url }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: redis_url
    - secretKey: dbHost
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbHost
    - secretKey: dbPort
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbPort
    - secretKey: dbName
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbName
    - secretKey: dbUser
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbUser
    - secretKey: dbPass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbPass
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: redis_url
    - secretKey: adminUserName
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: username
    - secretKey: adminPassword
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: password