---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-paperless
  namespace: media
spec:
  storageClassName: "smb"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-vol-paperless  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: //smb.${SECRET_DOMAIN}/services
      subDir: paperless
    nodeStageSecretRef:
      name: smb-secret
      namespace: kube-system