---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DB_CONNECTION: pgsql
        DB_DATABASE: &dbName firefly
        DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .FIREFLY__POSTGRESUSER }}"
        DB_PASSWORD: &dbPass "{{ .FIREFLY__POSTGRESPASS }}"
        DB_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## FIREFLY
    - secretKey: FIREFLY__POSTGRESUSER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: FIREFLY__POSTGRESUSER
    - secretKey: FIREFLY__POSTGRESPASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68747ca1-ad88-478b-9c15-f463dba76db5
        property: FIREFLY__POSTGRESPASS