---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SONARR__API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR__POSTGRESQL_NAME: &dbName sonarr
        SONARR__POSTGRESQL_HOST: &dbHost postgres-rw.database.svc.cluster.local
        SONARR__POSTGRESQL_USER: &dbUser "{{ .SONARR_POSTGRESQL_USER }}"
        SONARR__POSTGRESQL_PASSWORD: &dbPass "{{ .SONARR_POSTGRESQL_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## SONARR
    - secretKey: SONARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d0079122-c640-4977-8668-c597520413f9
        property: SONARR_API_KEY
    - secretKey: SONARR_POSTGRESQL_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d0079122-c640-4977-8668-c597520413f9
        property: SONARR_POSTGRESQL_USER
    - secretKey: SONARR_POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d0079122-c640-4977-8668-c597520413f9
        property: SONARR_POSTGRESQL_PASSWORD