---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65542 # gladius:external-services

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.1.0@sha256:91f3cd6b9f1c9988af5447f464b299630706eb7f691dee857eab1487d4bb626e
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                ${HOSTNAME}
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: api_key
              SABNZBD__NZB_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: nzb_key
            resources:
              requests:
                cpu: 5m
                memory: 1024Mi
              limits:
                memory: 6144Mi

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      media:
        existingClaim: nas-media
        globalMounts:
          - path: /data/nas-media
