---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # github_app_id, github_app_installation_id, github_app_private_key
        key: actions-runner-controller
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth-secret
  namespace: actions-runner-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PAPERLESS_DBHOST: |-
          {{ .dbHost }}
        PAPERLESS_DBPORT: |-
          {{ .dbPort }}
        PAPERLESS_DBNAME: |-
          {{ .dbName }}
        PAPERLESS_DBUSER: |-
          {{ .dbUser }}
        PAPERLESS_DBPASS: |-
          {{ .dbPass }}
        PAPERLESS_ADMIN_USER: |-
          {{ .adminUserName }}
        PAPERLESS_ADMIN_PASSWORD: |-
          {{ .adminPassword }}
        PAPERLESS_REDIS: |-
          {{ .redis_url }}
  refreshInterval: 15m
  data:
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: redis_url
    - secretKey: dbHost
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbHost
    - secretKey: dbPort
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbPort
    - secretKey: dbName
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbName
    - secretKey: dbUser
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbUser
    - secretKey: dbPass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: dbPass
    - secretKey: redis_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: redis_url
    - secretKey: adminUserName
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: username
    - secretKey: adminPassword
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: password