---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: media
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MINIO_ROOT_USER: |-
          {{ .root_username }}
        MINIO_ROOT_PASSWORD: |-
          {{ .root_password }}
  refreshInterval: 15m
  data:
    - secretKey: root_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9b752ef5-b90d-475b-b510-5d33f5a7b5c6
        property: username
    - secretKey: root_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9b752ef5-b90d-475b-b510-5d33f5a7b5c6
        property: password