---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2023-10-25T06-33-25Z
            args:
              - server
              - /data
              - --console-address
              - :9001
            env:
              MINIO_ROOT_USER:
                valueFrom:
                  secretKeyRef:
                    name: minio-secret
                    key: MINIO_ROOT_USER
              MINIO_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: minio-secret
                    key: MINIO_ROOT_PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
            securityContext:
              privileged: true
              runAsUser: 0

    service:
      main:
        ports:
          http:
            port: 9001
          s3:
            port: 9000

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: &host "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: s3

    persistence:
      config:
        enabled: true
        existingClaim: pvc-smb-minio
        mountPath: /data
