---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: minio
      app.kubernetes.io/instance: minio
      app.kubernetes.io/part-of: minio
