---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        WALLABAG_POSTGRESQL_NAME: &dbName wallabag
        WALLABAG_POSTGRESQL_HOST: &dbHost postgres-rw.database.svc.cluster.local
        WALLABAG_POSTGRESQL_USER: &dbUser "{{ .WALLABAG_POSTGRESQL_USER }}"
        WALLABAG_POSTGRESQL_PASSWORD: &dbPass "{{ .WALLABAG_POSTGRESQL_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## WALLABAG
    - secretKey: WALLABAG_POSTGRESQL_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: faa2188b-8e4d-4e6a-9490-07b3c3f9a2ad
        property: WALLABAG_POSTGRESQL_USER
    - secretKey: WALLABAG_POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: faa2188b-8e4d-4e6a-9490-07b3c3f9a2ad
        property: WALLABAG_POSTGRESQL_PASSWORD