---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        # POSTGRES_SUPER_USER: "{{ .username }}"
        # POSTGRES_SUPER_PASS: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 741ab874-d619-4bed-a307-8b67ea13f4c1
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 741ab874-d619-4bed-a307-8b67ea13f4c1
        property: password
