apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:/2oHaqes4ncvW+vvTiCo0GBJkj59DW22cfKf+gsbZurLzn9JhMkCY6FhBm90IUuuUlStC/18LPkntfQi,iv:++APHGlbwyN9OFUCaofZjm3QkxxJ0U+ruGOdbQcTnNM=,tag:Q/MWtK3EQ8xE4ms1k55aVA==,type:str]
    username: ENC[AES256_GCM,data:AnD6FDk=,iv:UJHtOYInJyHCaHhymOaY8Dn6JtFiMe/WW0+y8ZX/ebI=,tag:/W96tm/equl7XO0WPZ0gpg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySXpPSlRhNkpTM243dFpu
            UG1zOXVVZFZ1M1NkeVA2NkFmR0ZQVlE4WlJjClRoSlR2bnlxTjRqTVJkdU1oN2RN
            YVA1YXl1ZlUvdzRUM2pGTXZTVFhmRVEKLS0tIGlqR0pFVTdIcGRoZWdGbG9McWgw
            STNobmxpZ0haOXdrV1dEdFEzdFQ3VjQK4nkFUbJdfpL7qY/9LwoAqAsWgg3M/f1W
            4HPqBMwKbzUPn8fRCZLH20Ssp8AJeNAITCetPedZbmLUgYpx/8tVzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T09:58:56Z"
    mac: ENC[AES256_GCM,data:4ZylV7r7b5FjPa0Xb/6kQDjw4xpUrLo+uq+dlmt0yR5H0u2/M8qGImr7MSG2D2J/tfA0q5yLE22z7ru57/fhAp/jYaAbs3t35QhYgCYnvynukPxakfBl7TjWMXggf34p9qTKgiVvkyJmjuCi5L6WtA86dJsDnh7WNmm39b3rLms=,iv:pZZXxBFkmeWm0kf10QJf3VjSeEBK2TLFuFxXp9evGHQ=,tag:KXIQ447oIP9/q8P1W8srkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
