apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:Ea2FyV/9RC0kvTvwEsZo6kiE+AaZGTNVV9s5CfB99jFLREDi1btiPzUA6KN0EJS6vMTW0Vk9QWpMu9ix,iv:+XQ1us4qT1G30bh0nSlxwJbRqZLjwgD2LyrggRiCQzs=,tag:cJF5gVh6nctCydzixGfRgA==,type:str]
    username: ENC[AES256_GCM,data:8R1EsPw=,iv:aH2a54SAf7VKExbre+9Au5CGtD6dxg5OEq1+qIox1Es=,tag:eQFEwwH2gcFIKQlTsg7KQA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcWtpbm9aRjVrZ0QzcktF
            OXprdW4rY2dsald5UUsrV3lqNkZpR2NHUFdNCjdLemVmb1AwTFpkYWJnVWxTQW9y
            NkxnTFZ0SldFcmRwOTZHVUNPT1plbDAKLS0tIExSNUNTQ0lHbkhEeFN1SlNneFZL
            ZTJXMjBxMmYvbjUwdER3SytTTXk4WmcKZq1uRtOKZdYRPQwQYhnA3SuskJY7/xdB
            3qhNbiyIpScZDgxGl78Cogxv/y3wS2ml2KknJV/wyhegvN6ETe3c0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:56:14Z"
    mac: ENC[AES256_GCM,data:BQG7TBkebLyP1rsafpLbB3Cr/8hAOlGc2Qy0wG2SbxVFJTDCRcaMVOwAPSyhjNkvviefbxkal9c98FAqeSAPyiqCyRDdTlEJbNy3QrDcPH/AmNUQXsNx6BLWQvsPZ7Yf/tYyf3G9PpZcRsOXOdTLD9+h1CNWjvXWUfH8KWH1Xhc=,iv:FwLW0GmrH1newdUvwr8AZ7WGMhqOIrn1W7dxY2yQpYU=,tag:sl8uPcSlkWCLZMo6ZSfofQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
