---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bind-secret
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        BIND_RNDC_KEY: "{{ .BIND_RNDC_KEY }}"
  refreshInterval: 15m
  data:
    - secretKey: BIND_RNDC_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: faab954d-c9de-439c-838d-887982c568d3
        property: BIND_RNDC_KEY