apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WXdV1qIvX8OdIeFp39Tg2mO8PRzXew==,iv:C+cX3MsB9ZSg4sGBA0WB/EXDH1frbI6Y57S8ztvqvi0=,tag:Itej5gtjeahLC3Ym4Jj86g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZhPxzt9IQw/ocF9yAyba18SCfguL7tYFjq+RukX/hwdCwusR,iv:BCyKJYqLXTBYR9TIKr1ln7pb35HLAxKjkZarcVNv4RE=,tag:RT4yiIuH0KhbX97x6zCHvw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:K5WFSFosmuk72Sw0,iv:ZkbUDKAx8vL6IeUhgM8/pBBJp7KX4Wu4EP8qZSL3DlQ=,tag:URaiqSbFUtR2hRcMaK5+Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVlFnak1jTUtiZGkrNlNC
            V1Y4d0NCRS9aRDBFUFpKUitQcmZad3p4OWxzCllQWEo5SVZsQVBGSVJLcmN6QVZo
            ZHZ4cXZBNXV6Z2Y4MGgveDE3aFV1UDgKLS0tIE5admhaSlR1aDlnV0dYSzhiWWZO
            VnFHdWdPSUwwL28ya0tkNHFqTUlBenMKmOpyMn2qh10ygB4QHkA29IquPno4LyBe
            1QDtwbnbP23Fz1K/kol+uDmsZpkLoSZI8AxQHJWTcrW/NfmkmSWxpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:55:28Z"
    mac: ENC[AES256_GCM,data:PxA39CaBLjtJURgNQ4LzlgZ/vmIFGADKIbBDOQ5PZkjO5DVJrXM5+iUwk2bxx9IV9TQ3nwO5SpuFczGvhafpwExS/Vjhjepajg7hZUw+HODUzvz9cv/Th0eKavCa4xnIXK9933C25K8z0xfJenlENe80ly941MA2s0ZBhyPuX9Q=,iv:i3SgTEYeewPnQ/aVwCmtZNlFjfK0lmU2GslQnm6/zTQ=,tag:fPdG/u22b2qK6tNerjnKhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
