apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SVC_QBITTTORENT_ADDR: ENC[AES256_GCM,data:Wot27O4PABYmqF5N4Q==,iv:JKbLlFw5VG86cQOvMPnrGuOdLNRdX0qbgCAjXzOTnNs=,tag:WCeV+p0+Lk6oOcwo7iqtVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWTNNU3M0T0tFTFpGemxC
            NFphVU5odktVMlZEQm5vU1VGSGgzMno2cVJjCm10T0ZaSnVWc0tpWWFqTHFDcnRW
            aU92eDhwYXZjZnJ6cVdZdWE2UjdmU3MKLS0tICsvTEVvWWw4U3dCR2JzM2trUlhZ
            V1RGRzJlWHFzbmpFL0VhZW80SkZYYU0K4ezeF26SRplSLERNPToG5XCiggt54eFv
            omdlqf+wTmzl3zKoHnumFvpi9nsDfH4RnrPkwCKlMEQJRHMoPI/iQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T16:21:22Z"
    mac: ENC[AES256_GCM,data:yhbW8eY4tylfremx3qYnTAAqy5Qf1/xiWAdCusyaFy71mEqcsxvN9jsMzUWl0qL33x7udNI4fXlzzOF9t6rG9iZResef7JV/AgBkxPSIk/v4HFcJE2oYq0Qzbd/G3jbmCB9T1B7ku3q+ayvVViHRcxFtARa3zS8NKJPhFZQALQ0=,iv:WFQVJDAVsgNwbAK/H21XxWFCUKYQIaffQwoBsqEYTNg=,tag:TffdEHGeWQ7ggRwfUzf2QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
