apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:q7fP9ISTjJMJyGqj,iv:DClaqYjZTWjp/RWOrn5yT8F9rhwmSEJCle6EMXoyiWA=,tag:cS0cPilkj2wYa9oENbT+1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUjI3VlhDaC9hcVlUekZ5
            cndaNURVMTdVOUhoQlNSaGtVWlE0N3NqbnhrClViUkMxeFgwVzBPanBXbmV2ZGJx
            bWVTdjZHT3A1RVlIbGZnYVNKSWJvc1UKLS0tIG9CbmxQS0t1QjdhRFVIdEVxQXo1
            TVRtYU8xdFpoN1RjOTNjdnFBREp2SjQKLeVtYbj+nlbeXmYlq3VgHtWFb4gLU5y0
            pHb/TeJ9oQTj2bzfof9IwX9dDWzWVDD7vGsi2IKlkvUnk/7UeEeNog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T10:55:26Z"
    mac: ENC[AES256_GCM,data:RyulFwfQVvUxXqztgb4qBWYL09fcuPmMulYm+DT5fAROTgU6qLQlrDKmDmyUTIr0LJ+Rc3wMKKsZavUYk9x+96XB+mPj2x2iSe/NvYns3Zx/60mT3Rq1cZOuKHvutiXelKByEBEWLDSFjcx5AU6HsMOuK7+rNwYlAfX0/yNf63A=,iv:lLM4EEBpFFyXTpKRuJ72GuJecpDgnuhxKSk55SQS1HA=,tag:mWVuLo9y0fOck918STvnyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
