---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./external-services/ks.yaml
  - ./internal-dns/ks.yaml
  # - ./k8s-gateway/ks.yaml  ## DECOMISSIONED
  # - ./kutt/ks.yaml
  # - ./multus/ks.yaml
  - ./nginx/ks.yaml