---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset

        containers:
          main:
            resources:
              requests:
                cpu: 15m
                memory: 324Mi
              limits:
                memory: 600Mi
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.2.3
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            # resources:
            #   requests:
            #     cpu: 47m
            #     memory: 1254M
            #   limits:
            #     memory: 1254M

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config
        globalMounts:
          - path: /config
