apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1f97BoiPdl6I9T3qbJB6No64RvJRCptYaEr3JrMvByyH5lMC,iv:PDaLvbOEOwqhKt9+TTpPvk9Cu1oCGwI0GlczpQFlJHc=,tag:26Cai2zLNqNKngPwdv3z8Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:24Yvb8O1U8CcsohX/UEw8cIyd8CQrp4XZDI4JE02U+RdHbqvzi5hVGjJTQOgoVW0Y4LcqrnJRva1gjVdQA2xP1tqEXGqybZKLL8Jsnb3MEq12GnC3M8xfaSX6Ak1+Q4TIG0l1S07S01QAGUiOMH0FubC2V+BgYev+07korNaLCU4vq4k+JPVngS1fD6kS6nPOM4Mhh0bRg9s9vagQLZkKnimgscr29ikbJwiJ/P+qQ==,iv:OPC6kJuhOXVGn/7gwMIs+8cXTYxcr73OzXY8/9QwFxc=,tag:jPKYkB3KunYoTk0itNY3GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apaw0x3ja8ne4w08re4elvgt8wjhadpefelxjzhshf83834nhfzs65j7zp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVkZoSGdWdzVGUU9ZT1BY
            KzlFcS8wUzJROVhhZTZXbUtIYSt4TjRQUzM0ClBRdE93ckNiTXl4UlkwNnEvZ21C
            b2kxcUxJTTR5bm42MVA2ZVo3K0VCaWsKLS0tIFBEM2trSGhVRml6UXc2S0FmUk16
            d1lITjc0aE82SmxZK0ExMm9oM2tjYjAKGTuf7rtarEXYyhlM51yvPD1OraeUrvA5
            b03TYtYBfHdy+fWZDJ8xMqEZrCYy6OW9N2arYt1YbV0d5Tk8dnKb/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T21:29:22Z"
    mac: ENC[AES256_GCM,data:M2Rvm0gMEu6a5s/9j7Q52sNheq++4A69Vhg/rNMLEG5A0s6RytCmqitGfgnGLncrFqfXw6zPNyln4BBoD38dDEYoE1V93ngfAtWjrlUlrCysaCITvXODzc7h4dU+tdjKMZQn2Cl60wtlrMF2uk4Xsli/C4XHo/SBwWd2X8yvWZ0=,iv:ePcnKEOTa4Gd7NprkLmptWjBsLqggxIM8xlc4NfhkWI=,tag:CwbzhCwthS6zg8WNpxq4ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
