---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-redis
  namespace: media
spec:
  target:
    name: paperless-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_REDIS_PASSWORD: "{{ .PAPERLESS_REDIS_PASSWORD }}"
  data:
    ## PAPERLESS
    - secretKey: PAPERLESS_REDIS_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d4f6b8ae-e86e-422a-b550-c02ccb0ce544
        property: redis_secret