---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bonob-kids
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/simojenki/bonob
              tag: v0.6.11
            env:
              BNB_PORT: 4534
              BNB_SONOS_AUTO_REGISTER: true
              BNB_SONOS_DEVICE_DISCOVERY: true
              BNB_SONOS_SEED_HOST: 10.1.3.61
              BNB_SONOS_SERVICE_ID: 247
              BNB_SONOS_SERVICE_NAME: Library - Kids
              BNB_SUBSONIC_URL: https://navidrome-kids.bjw-s.dev
              BNB_URL: https://bonob-kids.bjw-s.dev
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: 4534

    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host bonob-kids.bjw-s.dev
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
