---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome-kids
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: ceph-block
              globalMounts:
                - path: /data

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.49.3
            env:
              ND_DATAFOLDER: /data
              ND_ENABLEDOWNLOADS: "true"
              ND_ENABLEEXTERNALSERVICES: "false"
              ND_ENABLESHARING: "false"
              ND_ENABLESTARRATING: "false"
              ND_LOGLEVEL: info
              ND_MUSICFOLDER: /music
              ND_PORT: &port 4533
              ND_SCANSCHEDULE: 30m
            resources:
              requests:
                cpu: 5m
                memory: 527M
              limits:
                memory: 527M

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.bjw-s.dev
        className: "external-nginx"
        hosts:
          - host: &host navidrome-kids.bjw-s.dev
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      music-kids:
        type: nfs
        server: nas.bjw-s.casa
        path: /volume1/Media/Library/Kids/Music
        globalMounts:
          - path: /music
            readOnly: true
