---
apiVersion: v1
kind: Service
metadata:
  name: ap
  namespace: networking
  labels:
    app.kubernetes.io/name: ap
    app.kubernetes.io/instance: ap
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: &port 80
      protocol: TCP
      targetPort: *port
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ap
subsets:
- addresses:
  - ip: 192.168.99.3
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ap
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ap.${SECRET_DOMAIN}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app.kubernetes.io/name: ap
    app.kubernetes.io/instance: ap
spec:
  ingressClassName: internal
  rules:
    - host: &host ap.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ap
                port:
                  number: 80
  tls:
    - hosts:
        - *host
   status:
    loadBalancer:
      ingress:
      - ip: 192.168.1.248
