---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wallabag
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        strategy: RollingUpdate

        pod:
          enableServiceLinks: false

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: wallabag-secret

        containers:
          main:
            image:
              repository: wallabag/wallabag
              tag: 2.6.7
            env:
              SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
              SYMFONY__ENV__DATABASE_HOST:
                valueFrom:
                  secretKeyRef:
                    name: wallabag-secret
                    key: WALLABAG_POSTGRESQL_HOST
              SYMFONY__ENV__DATABASE_PORT: 5432
              SYMFONY__ENV__DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: wallabag-secret
                    key: WALLABAG_POSTGRESQL_NAME
              SYMFONY__ENV__DATABASE_USER:
                valueFrom:
                  secretKeyRef:
                    name: wallabag-secret
                    key: WALLABAG_POSTGRESQL_USER
              SYMFONY__ENV__DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: wallabag-secret
                    key: WALLABAG_POSTGRESQL_PASSWORD
              SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${SECRET_DOMAIN}
              SYMFONY__ENV__SERVER_NAME: Wallabag
              SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
              SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
              POPULATE_DATABASE: "false"
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 256M

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "external"
        # annotations:
        #   external-dns.alpha.kubernetes.io/target: ingress-ext.${SECRET_DOMAIN}
        hosts:
          - host: &host "wallabag.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host