---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: joplin-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        POSTGRES_DATABASE: &dbName joplin
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .POSTGRESQL_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRESQL_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        MAILER_HOST: "{{ .SMTP_HOST }}"
        MAILER_AUTH_USER: "{{ .SMTP_USERNAME }}"
        MAILER_AUTH_PASSWORD: "{{ .SMTP_PASSWORD }}"
        MAILER_NOREPLY_EMAIL: "{{ .SMTP_FROM }}"
        # MAILER_HOST: smtp-relay.default.svc.cluster.local.
        # MAILER_PORT: 2525
        # MAILER_SECURITY: none
        # MAILER_NOREPLY_NAME: JoplinServer
        # MAILER_NOREPLY_EMAIL: joplin@${SECRET_DOMAIN}
  refreshInterval: 15m
  data:
    ## POSTGRES
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e579895-287a-4b26-976b-2677620dc376
        property: password
    ## joplin
    - secretKey: POSTGRESQL_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c30a48cd-c526-4522-9dc1-e0c4eb49cd79
        property: POSTGRESQL_USER
    - secretKey: POSTGRESQL_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c30a48cd-c526-4522-9dc1-e0c4eb49cd79
        property: POSTGRESQL_PASSWORD
    ## SMTP
    - secretKey: SMTP_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_HOST
    - secretKey: SMTP_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_PASSWORD
    - secretKey: SMTP_FROM
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 613150cc-5dcb-4b3e-881e-27cf5dbcad7e
        property: SMTP_FROM
