---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app joplin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: joplin-secret
        containers:
          main:
            image:
              repository: joplin/server
              tag: 2.13.5-beta
            env:
              APP_BASE_URL: https://joplin.${SECRET_DOMAIN}
              APP_PORT: &port 8080
              DB_CLIENT: pg
              # MAILER_ENABLED: 1
              # MAILER_HOST: smtp-relay.default.svc.cluster.local.
              # MAILER_PORT: 2525
              # MAILER_SECURITY: none
              # MAILER_NOREPLY_NAME: JoplinServer
              # MAILER_NOREPLY_EMAIL: joplin@${SECRET_DOMAIN}
            envFrom: *envFrom
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: "external"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Application Service
          gethomepage.dev/name: Joplin
          gethomepage.dev/description: Note Sync & Sharing Service
          gethomepage.dev/icon: https://raw.githubusercontent.com/chaijunkin/dashboard-icons/main/png/joplin.png
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "joplin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
